### ISSUE TITLE
Academic titles in front of the first name

### ISSUE THREAD

**Issue by domhardt** [salsod/komacv#2]
There are some german academic titles like Dipl.-Ing. or Dr.-Ing. that should be located in front of the first name. Komacv puts them in the row below the full name but it would be nice to have them in the row above the first name. I found no option to rearrange this.

**Comment by salsod** [comment]
Thanks for the suggestion.
Just added. See today's commit.

**Comment by domhardt** [comment]
Wow, thank you for that quick fix!

**Comment by salsod** [comment]
You're welcome!
